# Fixture Difficulty Rating Rotation Optimization

In FPL, Fixture Difficulty Rating (FDR) is a well-known metric. Simply put, FDR shows how difficult a team's game in every gameweek.

Finding pairs of teams that we can rotate is a common approach to simplify the FPL as a problem. Here, I will show how an FDR model can be written to find pairs, triplets, even under special conditions (e.g. FreeHit)

In [1]:
import pandas as pd
import sasoptpy as so
import requests
import json
import os
import random
from subprocess import Popen
from IPython.display import display, HTML

In [2]:
ratings = pd.read_csv("https://projects.fivethirtyeight.com/soccer-api/club/spi_global_rankings.csv")
ratings.head()

,rank,prev_rank,name,league,off,def,spi
0,1,1,Manchester City,Barclays Premier League,2.79,0.25,92.42
1,2,2,Bayern Munich,German Bundesliga,3.30,0.60,90.65
2,3,3,Chelsea,Barclays Premier League,2.42,0.20,90.53
3,4,4,Barcelona,Spanish Primera Division,3.14,0.56,90.10
4,5,5,Liverpool,Barclays Premier League,2.69,0.40,89.17

In [3]:
teams = {
    'ARS': {'name': 'Arsenal'},
    'AVL':  {'name': 'Aston Villa'},
    'BRT':  {'name': 'Brentford'},
    'BHU':  {'name': 'Brighton and Hove Albion'},
    'BUR':  {'name': 'Burnley'},
    'CHE':  {'name': 'Chelsea'},
    'CRY':  {'name': 'Crystal Palace'},
    'EVE':  {'name': 'Everton'},
    'LEI':  {'name': 'Leicester City'},
    'LEE': {'name':  'Leeds United'},
    'LIV': {'name':  'Liverpool'},
    'MCI': {'name':  'Manchester City'},
    'MUN': {'name':  'Manchester United'},
    'NEW': {'name':  'Newcastle'},
    'NOR': {'name':  'Norwich City'},
    'SOU': {'name':  'Southampton'},
    'TOT': {'name':  'Tottenham Hotspur'},
    'WAT': {'name':  'Watford'},
    'WHA': {'name':  'West Ham United'},
    'WOL': {'name':  'Wolverhampton'}
}

In [4]:
for team, val in teams.items():
    rating = ratings.loc[ratings.name == val['name'], 'spi'].values[0]
    val['rating'] = rating
teams

{'ARS': {'name': 'Arsenal', 'rating': 83.72},
 'AVL': {'name': 'Aston Villa', 'rating': 72.18},
 'BRT': {'name': 'Brentford', 'rating': 67.01},
 'BHU': {'name': 'Brighton and Hove Albion', 'rating': 78.71},
 'BUR': {'name': 'Burnley', 'rating': 66.79},
 'CHE': {'name': 'Chelsea', 'rating': 90.53},
 'CRY': {'name': 'Crystal Palace', 'rating': 61.55},
 'EVE': {'name': 'Everton', 'rating': 72.28},
 'LEI': {'name': 'Leicester City', 'rating': 78.22},
 'LEE': {'name': 'Leeds United', 'rating': 74.94},
 'LIV': {'name': 'Liverpool', 'rating': 89.17},
 'MCI': {'name': 'Manchester City', 'rating': 92.42},
 'MUN': {'name': 'Manchester United', 'rating': 85.53},
 'NEW': {'name': 'Newcastle', 'rating': 67.79},
 'NOR': {'name': 'Norwich City', 'rating': 65.03},
 'SOU': {'name': 'Southampton', 'rating': 67.01},
 'TOT': {'name': 'Tottenham Hotspur', 'rating': 78.06},
 'WAT': {'name': 'Watford', 'rating': 59.48},
 'WHA': {'name': 'West Ham United', 'rating': 76.0},
 'WOL': {'name': 'Wolverhampton', 'rating': 69.61}}

In [5]:
# Sets
team_list = list(teams.keys())
gameweeks = list(range(1,39))

In [6]:
# Random schedule
# Get values from Ben Crellin once it is available
fdr = {}
for week in range(1,39):
    for team in teams.keys():
        fdr[team, week] = random.random()

In [7]:
pd.set_option('display.max_columns', None)

In [8]:
def read_solution(m):
    with open('fdr.sol', 'r') as f:
        for v in m.get_variables():
            v.set_value(0)
        for line in f:
            if 'objective value' in line:
                continue
            words = line.split()
            v = m.get_variable(words[1])
            v.set_value(float(words[2]))

def print_solution(m):
    pick_team = m.get_variable('pick_team')
    pick_team_gw = m.get_variable('pick_team_gw')
    # Print solution
    selected_teams = []
    gameweek_picks = []
    for t in team_list:
        entry = {'team': t}
        if pick_team[t].get_value() > 0:
            selected_teams.append(t)
            for g in gameweeks:
                entry.update({g: round(pick_team_gw[t,g].get_value() * fdr[t,g], 3) })
            gameweek_picks.append(entry)
    print(f'Selected: {" and ".join(selected_teams)}. Total FDR: {round(m.get_objective_value(),3)}')
    pick_df = pd.DataFrame(gameweek_picks)
    s = pick_df.style
    colored_vals = lambda x: 'background-color: lightblue; color: black' if type(x) == float and x > 0 else 'color: white'
    s.applymap(colored_vals)
    display(HTML(s.render().replace("000", "")))
    return selected_teams

In [9]:
def solve_N_pair_problem(N=2, max_iter=1):
    m = so.Model(name='N_rotation_pairs')
    team_list = list(teams.keys())
    gameweeks = list(range(1,39))
    pick_team = m.add_variables(team_list, vartype=so.binary, name='pick_team')
    pick_team_gw = m.add_variables(team_list, gameweeks, vartype=so.binary, name='pick_team_gw')

    m.add_constraint(so.expr_sum(pick_team[t] for t in team_list) == N, name='pick_2')
    m.add_constraints((so.expr_sum(pick_team_gw[t, g] for t in team_list) == 1 for g in gameweeks), name='pick_1_per_gw')
    m.add_constraints((pick_team_gw[t,g] <= pick_team[t] for t in team_list for g in gameweeks), name='valid_picks_only')

    # Force using each team at least once
    m.add_constraints((so.expr_sum(pick_team_gw[t,g] for g in gameweeks) >= pick_team[t] for t in team_list), name='force_use')

    m.set_objective(so.expr_sum(fdr[t, g] * pick_team_gw[t, g] for t in team_list for g in gameweeks), sense='N', name='total_fdr')

    m.export_mps("fdr.mps")
    command = "cbc fdr.mps solve solu fdr.sol"
    Popen(command).wait()
    read_solution(m)
    selected_teams = print_solution(m)
    for it in range(1, max_iter):
        c = m.add_constraint(so.expr_sum(pick_team[t] for t in selected_teams) <= N-1, name=f'cutoff_{it}')
        m.export_mps("fdr.mps")
        Popen(command).wait()
        read_solution(m)
        selected_teams = print_solution(m)

In [10]:
solve_N_pair_problem(N=2, max_iter=3)

NOTE: Initialized model N_rotation_pairs.
Selected: BRT and TOT. Total FDR: 9.08

Selected: CRY and TOT. Total FDR: 9.381

Selected: BUR and WAT. Total FDR: 9.694

In [11]:
solve_N_pair_problem(N=3, max_iter=3)

NOTE: Initialized model N_rotation_pairs.
Selected: BUR and NOR and TOT. Total FDR: 6.713

Selected: BUR and SOU and TOT. Total FDR: 6.715

Selected: BRT and NOR and TOT. Total FDR: 6.844

In [12]:
# Free hit version
def solve_N_pair_problem_fh(N=2, max_iter=1):
    m = so.Model(name='N_rotation_pairs')
    team_list = list(teams.keys())
    gameweeks = list(range(1,39))
    pick_team = m.add_variables(team_list, vartype=so.binary, name='pick_team')
    pick_team_gw = m.add_variables(team_list, gameweeks, vartype=so.binary, name='pick_team_gw')
    pick_free_hit = m.add_variables(team_list, gameweeks, vartype=so.binary, name='pick_free_hit')

    m.add_constraint(so.expr_sum(pick_team[t] for t in team_list) == N, name='pick_2')
    m.add_constraints((so.expr_sum(pick_team_gw[t, g] + pick_free_hit[t, g] for t in team_list) == 1 for g in gameweeks), name='pick_1_per_gw')
    m.add_constraints((pick_team_gw[t,g] <= pick_team[t] for t in team_list for g in gameweeks), name='valid_picks_only')
    m.add_constraint((so.expr_sum(pick_free_hit[t, g] for t in team_list for g in gameweeks) <= 1), name='single_free_hit')

    # Force using each team at least once
    m.add_constraints((so.expr_sum(pick_team_gw[t,g] for g in gameweeks) >= pick_team[t] for t in team_list), name='force_use')

    m.set_objective(so.expr_sum(fdr[t, g] * (pick_team_gw[t, g] + pick_free_hit[t,g]) for t in team_list for g in gameweeks), sense='N', name='total_fdr')

    m.export_mps("fdr.mps")
    command = "cbc fdr.mps solve solu fdr.sol"
    Popen(command).wait()
    read_solution(m)

    def print_free_hit_sol():
        selected_teams = []
        gameweek_picks = []
        for t in team_list:
            entry = {'team': t}
            if pick_team[t].get_value() > 0 or so.expr_sum(pick_free_hit[t,g] for g in gameweeks).get_value() > 0:
                selected_teams.append(t)
                for g in gameweeks:
                    entry.update({g: round((pick_team_gw[t,g] + pick_free_hit[t,g]).get_value() * fdr[t,g], 3) })
                gameweek_picks.append(entry)
        print(f'Selected: {" and ".join(selected_teams)}. Total FDR: {round(m.get_objective_value(),3)}')
        pick_df = pd.DataFrame(gameweek_picks)
        s = pick_df.style
        colored_vals = lambda x: 'background-color: lightblue; color: black' if type(x) == float and x > 0 else 'color: white'
        s.applymap(colored_vals)
        display(HTML(s.render().replace("000", "")))
        return selected_teams

    selected_teams = print_free_hit_sol()
    for it in range(1, max_iter):
        c = m.add_constraint(so.expr_sum(pick_team[t] for t in selected_teams) <= N-1, name=f'cutoff_{it}')
        m.export_mps("fdr.mps")
        Popen(command).wait()
        read_solution(m)
        selected_teams = print_free_hit_sol()

In [13]:
solve_N_pair_problem_fh(2, 3)

NOTE: Initialized model N_rotation_pairs.
Selected: BRT and MUN and TOT. Total FDR: 8.48

Selected: CHE and CRY and TOT. Total FDR: 8.58

Selected: BUR and MUN and TOT. Total FDR: 8.89